// =============================================================================
// seed-users.mjs — seed verified (and optionally not-onboarded) test users into
// the LOCAL miniflare D1 (`.wrangler/state`), so the E2E suite can log in
// through the real /login flow without going through the OTP-via-Resend signup.
// =============================================================================
//
// The password hash uses `hashPassword` from `better-auth/crypto` — the SAME
// function Better Auth's runtime uses at sign-in — so the seeded credentials
// always verify against the real /api/auth/sign-in/email path. No dev bypass,
// no shortcut: the real auth flow accepts them.
//
// Tables + columns match migrations/0002_camelcase.sql (the actual camelCase
// schema in the local DB). See packages/hono-worker/migrations/.
//
// Idempotent: deletes any prior rows for the seed emails first, so re-running
// locally or in CI yields the same starting state.
//
// All SQL runs as ONE `wrangler d1 execute --file` invocation. This matters:
// each separate --local invocation boots its own miniflare, and individual
// statements can land in different snapshots (or no-op silently). A single
// file keeps the whole seed in one connection/transaction.

import { hashPassword } from "better-auth/crypto"
import { execFile } from "node:child_process"
import { promisify } from "node:util"
import { randomUUID } from "node:crypto"
import { fileURLToPath } from "node:url"
import { dirname, resolve } from "node:path"
import { writeFileSync, unlinkSync, mkdtempSync } from "node:fs"
import { tmpdir } from "node:os"

const execFileAsync = promisify(execFile)

const __dirname = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolve(__dirname, "..", "..", "..")
const WORKER_DIR = resolve(REPO_ROOT, "packages", "hono-worker")
// Resolve the wrangler CLI JS directly (avoids npx + Windows-shell quoting
// issues — spaces in the SQL were being split by cmd.exe when going through
// `npx` with shell:true).
const WRANGLER_BIN = resolve(REPO_ROOT, "node_modules", "wrangler", "bin", "wrangler.js")

const DB_NAME = "agent-harness-auth"
const PASSWORD = process.env.E2E_PASSWORD ?? "Test1234!"
const now = () => Date.now()

// IMPORTANT: wrangler d1 execute --local and wrangler dev resolve their local
// persistence to slightly different default paths, so a plain `--local` write
// can land in a snapshot the dev server never sees (silent no-op). Pin both to
// the SAME explicit path: <worker>/.wrangler/state — exactly where `wrangler dev`
// in packages/hono-worker reads from.
const PERSIST_TO = ".wrangler/state"

const USERS = [
  {
    email: process.env.E2E_USER_A_EMAIL ?? "e2e-a@example.test",
    name: "E2E User A",
    onboardingComplete: 1, // fully onboarded
  },
  {
    email: process.env.E2E_USER_B_EMAIL ?? "e2e-b@example.test",
    name: "E2E User B",
    onboardingComplete: 1, // fully onboarded
  },
  {
    email: process.env.E2E_USER_NO_EMAIL ?? "e2e-no@example.test",
    name: "E2E Not Onboarded",
    onboardingComplete: 0, // exercises the 428 → /onboarding path
  },
]

/** Wrap a JS string as a SQL single-quoted string literal. */
function sqlStr(s) {
  return `'${String(s).replace(/'/g, "''")}'`
}

/**
 * Write a .sql file with the full seed (DELETE + INSERTs) and execute it in one
 * `wrangler d1 execute --file` call.
 */
async function d1ExecFile(sqlFilePath) {
  try {
    await execFileAsync(process.execPath, [
      WRANGLER_BIN,
      "d1",
      "execute",
      DB_NAME,
      "--local",
      "--persist-to",
      PERSIST_TO,
      "--file",
      sqlFilePath,
    ], {
      cwd: WORKER_DIR,
      encoding: "utf8",
    })
  } catch (err) {
    throw new Error(
      `wrangler d1 execute --file failed:\n  stderr: ${err.stderr ?? ""}\n  stdout: ${err.stdout ?? ""}`,
    )
  }
}

async function seed() {
  console.log("[seed] hashing password with better-auth/crypto#hashPassword…")
  const passwordHash = await hashPassword(PASSWORD)
  console.log(`[seed] password hash: ${passwordHash.slice(0, 24)}…`)

  // Build ONE script: wipe the auth tables (children before parent to clear any
  // orphaned accounts), then insert every user + account row.
  const emailList = USERS.map((u) => sqlStr(u.email)).join(", ")
  const lines = [
    `-- auto-generated by packages/e2e/scripts/seed-users.mjs`,
    `DELETE FROM "session";`,
    `DELETE FROM "account";`,
    `DELETE FROM "verification";`,
    `DELETE FROM "user" WHERE email IN (${emailList});`,
    `-- Enable FK enforcement for the inserts below.`,
    `PRAGMA foreign_keys = ON;`,
  ]

  for (const u of USERS) {
    const userId = randomUUID()
    const accountId = randomUUID()
    const ts = now()

    lines.push(
      `INSERT INTO "user"`,
      `  ("id","email","emailVerified","name","image","createdAt","updatedAt","onboardingComplete")`,
      `VALUES`,
      `  (${sqlStr(userId)}, ${sqlStr(u.email)}, 1, ${sqlStr(u.name)}, NULL, ${ts}, ${ts}, ${u.onboardingComplete});`,
      `INSERT INTO "account"`,
      `  ("id","accountId","providerId","userId","accessToken","refreshToken",`,
      `   "accessTokenExpiresAt","refreshTokenExpiresAt","scope","idToken","password","createdAt","updatedAt")`,
      `VALUES`,
      `  (${sqlStr(accountId)}, ${sqlStr(userId)}, ${sqlStr("credential")}, ${sqlStr(userId)},`,
      `   NULL, NULL, NULL, NULL, NULL, NULL, ${sqlStr(passwordHash)}, ${ts}, ${ts});`,
    )
    console.log(
      `[seed] staged ${u.email} (onboardingComplete=${u.onboardingComplete})`,
    )
  }

  const sql = lines.join("\n")
  const tmpDir = mkdtempSync(resolve(tmpdir(), "e2e-seed-"))
  const sqlFile = resolve(tmpDir, "seed.sql")
  writeFileSync(sqlFile, sql, "utf8")

  try {
    console.log(`[seed] executing ${lines.length} statements via wrangler…`)
    await d1ExecFile(sqlFile)
    console.log(`[seed] ✓ done — ${USERS.length} users seeded into local D1.`)
  } finally {
    try {
      unlinkSync(sqlFile)
    } catch {
      // best-effort cleanup
    }
  }
}

seed().catch((err) => {
  console.error("[seed] FAILED:", err)
  process.exit(1)
})
