import { createRouter } from "@tanstack/react-router"
// Generated by @tanstack/router-plugin from src/routes/. Regenerated on every
// dev/build. Imported via relative path (same convention as the official
// start-basic-cloudflare example).
import { routeTree } from "./routeTree.gen"

// The app router factory. TanStack Start calls getRouter() per-request on the
// server (so each SSR request gets its own router instance) and once on the
// client. defaultPreload "intent" prefetches a route's loaders on hover/focus
// for fast navigation. Browser history (no hash) — SSR needs real URLs.
export function getRouter() {
  return createRouter({
    routeTree,
    defaultPreload: "intent",
    scrollRestoration: true,
  })
}

// Register the router type for type-safe Link/useParams/useLoaderData.
declare module "@tanstack/react-router" {
  interface Register {
    router: ReturnType<typeof getRouter>
  }
}
